apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect4-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connect4
  template:
    metadata:
      labels:
        app: connect4
    spec:
      containers:
      - name: connect4-app
        image: moonlovesmoon/connect4-app:latest # You have to use your dockerhub username here
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: connect4-service
spec:
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  
  selector:
    app: connect4